### ISSUE TITLE
Use .thing files for configuration

### ISSUE THREAD

**Issue by nwootton** [Nebula83/openhab2-addons#10]
Allow users to define their EvoHome gateway and associated things via configuration '.thing' file.

**Comment by nwootton** [comment]
Using 'evohome.things' file that lists the gateway appears to work.
```
Bridge evohome:gateway:76aae5f4 [ username="myEmail", password="mySecret", applicationId="b013aa26-9724-4dbd-8897-048b9aada249"] 
```
It allows the gateway to appear in the PaperUI, from where you can scan for the various individual radiators, displays etc etc.

Not persuaded the file to allow me to include the individual things.

**Comment by stefanoboccato** [comment]
Yep! Same thing! I try create a .thing file, but a NumberFormatException: null occurs.

ne:myhome:matrimoniale' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): null
14:07:38.013 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'evohome:heatingzone:myhome:matrimoniale': java.lang.NumberFormatException: null
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)[99:org.eclipse.smarthome.core:0.9.0.b5]

**Comment by nwootton** [comment]
Are you using the "refreshInterval" value in your .thing file?

I found that you had to treat it as a proper integer to avoid the "NumberFormatException" error

```
refreshInterval=15000
```
rather than
```
refreshInterval="15000"
```

**Comment by stefanoboccato** [comment]
this is my .thing file:

`Bridge evohome:gateway:myhome [ username="xxx@gmail.com", password="xxxxxxxx", refreshInterval=15000]`
`{`
`	Thing evohome:display:myhome:EvoTouch `
`	Thing evohome:heatingzone:myhome:matrimoniale`
`}`

**Comment by nwootton** [comment]
OK. I hit that NumberFormatException bug with the quotes in the gateway definition. I had different errors when I added individual things.

Interestingly, the error only throws over the 
```
evohome:heatingzone:myhome:matrimoniale
```

item. No idea why not over the 

```
Thing evohome:display:myhome:EvoTouch
```

I guess we'll have to wait for Nebula83 to look at it and provide some insight.

**Comment by foxy82** [comment]
I suspect you need to add the id somewhere. It's been a while since I wrote
this but I think I used the id rather than the text name which risked
having duplicates.

Neil

**Comment by foxy82** [comment]
So I've just checked and these are the properties I set on a heating zone:

LOCATION_ID
ZONE_ID
ZONE_NAME
ZONE_TYPE
ZONE_MODEL_TYPE

I don't know about defining thing files but from the bridge definition above I'd guess they would need to be in square brackets. Note: they are upper case as shown. The values are from the json you receive from evohome.

**Comment by nwootton** [comment]
Hi Neil,

Using a just simple gateway definition in a .thing file works fine:
```
Bridge evohome:gateway:11aaa1a1 [ username="username@email.com", password="supersecretword", applicationId="b013aa26-9724-4dbd-8897-048b9aada249", refreshInterval=15000]
```
This gives you a working EvoHome account in the PaperUI, that then allows you to search and add each item in the EvoHome system. If you examine the jsondb and look at the _things_ that get created they are in this format

```
evohome:heatingzone:11aaa1a1:Master
```

The errors start to appear when you try to use this format to predefine or add the individual items into the .thing file at the start. My full file was this

```
Bridge evohome:gateway:11aaa1a1 [ username="username@email.com", password="supersecretword", applicationId="b013aa26-9724-4dbd-8897-048b9aada249", refreshInterval=15000]
{
    Thing evohome:display:11aaa1a1:EvoTouch
    Thing evohome:heatingzone:11aaa1a1:Lounge
    Thing evohome:heatingzone:11aaa1a1:Snug
    Thing evohome:heatingzone:11aaa1a1:Kitchen
    Thing evohome:heatingzone:11aaa1a1:NewRoom
    Thing evohome:heatingzone:11aaa1a1:Hall
    Thing evohome:heatingzone:11aaa1a1:Toilet
    Thing evohome:heatingzone:11aaa1a1:Bed1
    Thing evohome:heatingzone:11aaa1a1:Bed2
    Thing evohome:heatingzone:11aaa1a1:Master
    Thing evohome:heatingzone:11aaa1a1:Study
}
```
Initial start up of OH 2.1 gives the following message for each .thing file item:

```
Validation issues found in configuration model 'evohome.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
```
When you then open up the PaperUI it throws handler errors in the logs:
```
2017-07-04 08:30:54.674 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'evohome:heatingzone:76aae5f4:NewRoom': java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
```
And the paper UI lists the working EvoHome account and each .thing is listed with a grey 'UNINITIALIZED - HANDLER_INITIALIZING_ERROR' error for the status.

The errors appear everytime I start OH, so it's not just a first run issue that we see with the binding itself.

I've tried not having the word Thing in front of each item, I've tried adding commas to the end of the lines and I've tried adding [_room name_] to each item

```
Thing evohome:heatingzone:11aaa1a1:Lounge [Lounge]
```
Nothing I do allows me to define the individual items.

**Comment by nwootton** [comment]
So busy typing I missed your comment!

By ID do you mean the EvoHome ID a 700000 type number instead of the room name?

```
Thing evohome:heatingzone:11aaa1a1:7000000 [Lounge]
```

**Comment by foxy82** [comment]
The thingId in code uses the zoneId. i think openhab then gives it some unique ID as well.

So i think you need...

Thing evohome:heatingzone:<zoneId>


where zoneId is from the json

{ "zoneId": "12345", "temperatureStatus": { "temperature": 20.0, "isAvailable": true }, "activeFaults": [], "heatSetpointStatus": { "targetTemperature": 15.0000, "setpointMode": "FollowSchedule" }, "name": "Bed2" },


e.g.
Thing evohome:heatingzone:12345

Or maybe it is this if it includes the unique id;
Thing evohome:heatingzone:12345:11aaa1a1

**Comment by foxy82** [comment]
Thing evohome:heatingzone:zoneId

Seems github cut that line

**Comment by stefanoboccato** [comment]
I had tried it yet, but when openhab discover the Evohome thing, and get it
also from the configuration file (the same thing, with the same id numbers)
it correctly warn for a conflict.
I search for disable auto discover, found something, but the configurations
I've found doesnt' work

2017-07-07 9:27 GMT+02:00 foxy82 <notifications@github.com>:

**Comment by nwootton** [comment]
Ok, been testing LOTS of thing definition combinations without success. I'm adding each of the following as a single entry under the gateway in the .thing file, I've then restarted OH and checked the logs. If it failed I stopped OH, cleared the logs, modified the .thing file with the next attempt and re-started OH.

_123456_ is the zoneid from EvoHome
_11aaa1a1_ is the OH Gateway ID
_Lounge_ is used in EvoHome and OH to identify the room

The following fail because they are incorrectly formed
```
Thing evohome:heatingzone:11aaa1a1 Lounge
Thing evohome:heatingzone:123456 Lounge
Thing evohome:heatingzone:123456:11aaa1a1 Lounge
Thing evohome:heatingzone:11aaa1a1:123456 Lounge

Thing evohome:heatingzone:11aaa1a1 [Lounge]
Thing evohome:heatingzone:123456 [Lounge]
Thing evohome:heatingzone:123456:11aaa1a1 [Lounge]
Thing evohome:heatingzone:11aaa1a1:123456 [Lounge]
```
The following fail with the same error:
```
Thing evohome:heatingzone:123456

Thing evohome:heatingzone:123456:11aaa1a1
Thing evohome:heatingzone:11aaa1a1:123456

Thing evohome:heatingzone:11aaa1a1:Lounge
Thing evohome:heatingzone:123456:Lounge
Thing evohome:heatingzone:123456:11aaa1a1:Lounge
Thing evohome:heatingzone:11aaa1a1:123456:Lounge

Thing evohome:heatingzone:11aaa1a1 "Lounge"
Thing evohome:heatingzone:123456 "Lounge"
Thing evohome:heatingzone:123456:11aaa1a1 "Lounge"
Thing evohome:heatingzone:11aaa1a1:123456 "Lounge"

Thing evohome:heatingzone:11aaa1a1 [name="Lounge"]
Thing evohome:heatingzone:123456 [name="Lounge"]
Thing evohome:heatingzone:123456:11aaa1a1 [name="Lounge"]
Thing evohome:heatingzone:11aaa1a1:123456 [name="Lounge"]

Thing evohome:heatingzone:11aaa1a1 [zoneid=123456, name="Lounge"]
Thing evohome:heatingzone:123456 [zoneid=123456, name="Lounge"]
Thing evohome:heatingzone:123456:11aaa1a1 [zoneid=123456, name="Lounge"]
Thing evohome:heatingzone:11aaa1a1:123456 [zoneid=123456, name="Lounge"]
```
The error is
```
2017-07-07 11:31:43.397 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'evohome.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
2017-07-07 11:31:43.397 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'evohome.things'
2017-07-07 11:31:43.410 [INFO ] [vohome.handler.EvohomeGatewayHandler] - Initializing Evohome Gateway handler.
2017-07-07 11:31:43.411 [INFO ] [home.internal.api.EvohomeApiClientV2] - Creating Evohome API client.
2017-07-07 11:31:43.419 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'evohome:heatingzone:123456': java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
```


If I just add the gateway via .thing and then do a search in the PaperUI I get the following in the events.log
```
2017-07-07 11:32:52.031 [InboxAddedEvent           ] - Discovery Result with UID 'evohome:display:11aaa1a1:EvoTouch' has been added.
2017-07-07 11:32:52.042 [InboxAddedEvent           ] - Discovery Result with UID 'evohome:heatingzone:11aaa1a1:Lounge' has been added.
```

If I then manually add the Lounge via PaperUI
```
2017-07-07 11:33:20.578 [ThingAddedEvent           ] - Thing 'evohome:heatingzone:11aaa1a1:Lounge' has been added.
2017-07-07 11:33:20.579 [hingStatusInfoChangedEvent] - 'evohome:heatingzone:11aaa1a1:Lounge' changed from UNINITIALIZED to INITIALIZING
2017-07-07 11:33:20.592 [ItemStateChangedEvent     ] - Temperature_GF_Lounge changed from NULL to 23.0
2017-07-07 11:33:20.603 [hingStatusInfoChangedEvent] - 'evohome:heatingzone:11aaa1a1:Lounge' changed from INITIALIZING to ONLINE
2017-07-07 11:33:20.609 [ItemStateChangedEvent     ] - Heating_GF_Lounge changed from NULL to 15.0
2017-07-07 11:33:20.611 [ItemStateChangedEvent     ] - Heating_Status_GF_Lounge changed from NULL to FollowSchedule
```

This seems to indicate that the correct format would be 
```
Thing evohome:heatingzone:11aaa1a1:Lounge
```
So I'm still confused why adding it in this format to the .thing file throws errors, yet OH happily lists this in the PaperUI using the same name if I don't add it via the .thing file.

**Comment by Nebula83** [comment]
Fixed in the upcoming release
