### ISSUE TITLE
[Evohome] binding keeps holding the state initializing

### ISSUE THREAD

**Issue by webnar** [Nebula83/openhab2-addons#12]
## Expected Behavior
setup connection with honeywell cloud

## Current Behavior
Binding keep stating intitializing. It doe not connect to Honeywell

2017-08-11 17:01:25.628 [DEBUG] [nding.evohome.internal.api.ApiAccess] - Requesting: [https://tccna.honeywell.com/Auth/OAuth/Token]
2017-08-11 17:01:27.086 [DEBUG] [nding.evohome.internal.api.ApiAccess] - Response: HttpContentResponse[HTTP/1.1 200 OK - 1454 bytes]
Set-Cookie: tccna=R3129434687; path=/; expires=Sat, 12-Aug-2017 15:17:31 GMT

{"access_token":"dR4vbyj.......93Drp-LTGF4","scope":"EMEA-V1-Basic EMEA-V1-Anonymous"}
2017-08-11 17:01:27.095 [DEBUG] [nding.evohome.internal.api.ApiAccess] - Requesting: [https://tccna.honeywell.com/WebAPI/emea/api/v1/userAccount]
2017-08-11 17:01:27.212 [DEBUG] [nding.evohome.internal.api.ApiAccess] - Response: HttpContentResponse[HTTP/1.1 400 Bad Request - 167 bytes]
Set-Cookie: tccna=R3709470637; path=/; expires=Sat, 12-Aug-2017 15:17:31 GMT
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=UTF-8
Expires: -1
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Server: Web1
Date: Fri, 11 Aug 2017 15:01:26 GMT
Content-Length: 167

[
  {
    "code": "UnsupportedClientVersion",
    "message": "Values provided by API aren't supported by client or field filled by client is not supported."
## Environment
Iam running openhabian on RPI3 Jessie have binding 2.1.1 for evohome

**Comment by Nebula83** [comment]
Thanks for reporting this! The logging helps as well. Would you mind telling me which country you are trying to connect from?

**Comment by deGit78** [comment]
Hi, I have the same problem

I log in to the German TCC site.
Something is interesting:
If I create on the German tcc a user who is allowed to control my thermostats, and use this account in the binding, the status reaches online (of course with no zones, etc)
Hope that helps?
If you like I can add my log file too.

Dennis

**Comment by deGit78** [comment]
Hi, 
is there any chance that the problem will be solved?
Someone working on?

**Comment by M1cN** [comment]
Hi Dennis,

Iam using org.openhab.binding.evohome-2.3.0-SNAPSHOT binding and that one is working for me with the extra added account i created in TCC.

**Comment by Nebula83** [comment]
@deGit78 have you tried the latest version? I'd be happy to know if this can be closed.

**Comment by Nebula83** [comment]
@webnar so according to you the issue can be closed?

**Comment by M1cN** [comment]
Hi Nebula,

yes for me it's all working now.



Op di 10 apr. 2018 21:14 schreef Nebula83 <notifications@github.com>:

**Comment by Nebula83** [comment]
Good, then I am closing it. Feel free to reopen when you experience this issue again.
