### ISSUE TITLE
Evohome] binding keeps holding the state initializing

### ISSUE THREAD

**Issue by deGit78** [Nebula83/openhab2-addons#16]
## Expected Behavior
setup connection with honeywell cloud

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment
Raspian on pi2

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by deGit78** [comment]
I log in to the German TCC site.
Something is interesting:
If I create on the German tcc a user who is allowed to control my thermostats, and use this account in the binding, the status reaches online (of course with no zones, etc)
Hope that helps?
If you like I can add my log file too.

Dennis

**Comment by deGit78** [comment]
Expected Behavior
setup connection with honeywell cloud

**Comment by Nebula83** [comment]
I'm currently reworking a large part of the binding. When I'm done I'll make a new release. Could I ask you to try again with this new release when I completed it?

**Comment by deGit78** [comment]
Hi,

Yes of course.
Please let me know when I can help with more details.



Am 1. März 2018 20:18:45 schrieb Nebula83 <notifications@github.com>:

**Comment by Nebula83** [comment]
Duplicate : https://github.com/Nebula83/openhab2-addons/issues/12
