### ISSUE TITLE
v.2.4.0 No binding found that supports creating a thing of type 'evohome:account'.  

### ISSUE THREAD

**Issue by gck303** [Nebula83/openhab2-addons#27]
I have installed the binding by adding the jar to my addons directory. 

I now go into the paperUI and add a new thing for the account. I put in my username and password. But, the new thing never gets past the uninitialized status. 

## Expected Behavior
I would expect that the new account connects and moves to a ONLINE status. 

## Current Behavior
The following message appears in the log files:
06:28:32.635 [WARN ] [core.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type 'evohome:account'.  

openhab> bundle:list | grep evo                                                                                     
231 │ Waiting  │  80 │ 2.4.0                  │ evohome Binding

## Possible Solution
It seems to me that there is a problem in the way the 

## Steps to Reproduce (for Bugs)
1. add the binding file into the addons
2.create the account thing
3. it should connect, it does not

## Context
The binding cannot be used without a working and connecting account. The evohome:account type is available within the paperui, but it cannot be called. 

## Your Environment
Openhab 2.2.0. Installed as a docker container on a qnap NAS. 
Binding jar version 2.4.0

**Comment by gck303** [comment]
Resolved. It was because I was using the 2.4.0 binding with a 2.2.0 openhab. 

Hopefully this issue will help someone else safe a lot of time!

**Comment by Nebula83** [comment]
Just what I wanted to comment :-) 

> Your Environment
> Openhab 2.2.0. Installed as a docker container on a qnap NAS.
> Binding jar version 2.4.0

Glad it is working for you now!
